package com.popov.mediacataloguer.swing.dialogs;

import com.popov.mediacataloguer.service.Settings;
import com.popov.mediacataloguer.service.SettingsProvider;
import com.popov.mediacataloguer.swing.Utils;
import com.popov.mediacataloguer.swing.model.ImportProfileTableModel;
import com.popov.mediacataloguer.utils.icons.IconKind;
import com.popov.mediacataloguer.utils.icons.IconProvider;
import com.popov.mediacataloguer.utils.icons.IconTarget;

import javax.inject.Inject;
import javax.inject.Provider;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class MainWindow extends JFrame {
    private JPanel contentPane;
    private JButton buttonClose;
    private JButton buttonMediaProfileCreate;
    private JButton buttonMediaProfileEdit;
    private JButton buttonMediaProfileRemove;
    private JTable tableImportProfiles;

    final private Settings settings;
    final private ImportProfileTableModel importProfileTableModel;
    final private IconProvider iconProvider;
    final private Provider<MediaProfileEditDialog> mediaProfileEditDialogProvider;

    @Inject
    public MainWindow(
            Settings settings,
            IconProvider iconProvider,
            ImportProfileTableModel importProfileTableModel,
            Provider<MediaProfileEditDialog> mediaProfileEditDialogProvider
    ) {
        this.settings = settings;
        this.iconProvider = iconProvider;
        this.importProfileTableModel = importProfileTableModel;
        this.mediaProfileEditDialogProvider = mediaProfileEditDialogProvider;

        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonClose);

        buttonClose.addActionListener(event -> dispose());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        contentPane.registerKeyboardAction(event -> dispose(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        tableImportProfiles.setModel(importProfileTableModel);
        buttonMediaProfileCreate.setIcon(iconProvider.getIcon(IconKind.Create, IconTarget.Button));
        buttonMediaProfileEdit.setIcon(iconProvider.getIcon(IconKind.Edit, IconTarget.Button));
        buttonMediaProfileRemove.setIcon(iconProvider.getIcon(IconKind.Remove, IconTarget.Button));

        buttonMediaProfileCreate.addActionListener(this::buttonMediaProfileCreateOnClicked);
        buttonMediaProfileEdit.addActionListener(this::buttonMediaProfileEditOnClicked);
        buttonMediaProfileRemove.addActionListener(this::buttonMediaProfileRemoveOnClicked);

        pack();
        setIconImage(iconProvider.getIcon(IconKind.FolderOpen, IconTarget.WindowIcon).getImage());
        setTitle("Media cataloguer");
        Utils.replaceWindow(this);
    }

    private void buttonMediaProfileCreateOnClicked(ActionEvent actionEvent) {
        MediaProfileEditDialog mediaProfileEditDialog = mediaProfileEditDialogProvider.get();
        if (mediaProfileEditDialog.exec() == ExecDialog.Result.Accepted) {
            settings.getImportProfiles().add(mediaProfileEditDialog.getImportProfile());
            settings.fireSettingsChanged();
        }
    }

    private void buttonMediaProfileEditOnClicked(ActionEvent actionEvent) {
        MediaProfileEditDialog mediaProfileEditDialog = mediaProfileEditDialogProvider.get();
        mediaProfileEditDialog.setAction(MediaProfileEditDialog.Action.Edit);
        if (mediaProfileEditDialog.exec() == ExecDialog.Result.Accepted) {
            settings.fireSettingsChanged();
        }
    }

    private void buttonMediaProfileRemoveOnClicked(ActionEvent actionEvent) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonMediaProfileCreate = new JButton();
        buttonMediaProfileCreate.setHideActionText(false);
        buttonMediaProfileCreate.setHorizontalAlignment(2);
        buttonMediaProfileCreate.setHorizontalTextPosition(4);
        buttonMediaProfileCreate.setText("Create");
        panel1.add(buttonMediaProfileCreate, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tableImportProfiles = new JTable();
        panel1.add(tableImportProfiles, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 5, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        buttonMediaProfileEdit = new JButton();
        buttonMediaProfileEdit.setHorizontalAlignment(2);
        buttonMediaProfileEdit.setHorizontalTextPosition(4);
        buttonMediaProfileEdit.setText("Edit");
        panel1.add(buttonMediaProfileEdit, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonMediaProfileRemove = new JButton();
        buttonMediaProfileRemove.setHorizontalAlignment(2);
        buttonMediaProfileRemove.setHorizontalTextPosition(4);
        buttonMediaProfileRemove.setText("Remove");
        panel1.add(buttonMediaProfileRemove, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonClose = new JButton();
        buttonClose.setText("Close");
        panel1.add(buttonClose, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
